<a href="https://colab.research.google.com/github/vijayanand2425/File-Handling-15sums-.ipynb/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list=[4,5,6,7,8,15]
array=np.array(list)
array

array([ 4,  5,  6,  7,  8, 15])

In [3]:
np.arange(3)

array([0, 1, 2])

In [4]:
np.arange(5,101)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100])

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [30]:
np.random.rand(5)

array([0.76449971, 0.8539131 , 0.00387452, 0.65489602, 0.09755535])

In [32]:
np.random.rand(2,5)

array([[0.92854394, 0.1933533 , 0.03186238, 0.17813344, 0.84934688],
       [0.82397391, 0.61060195, 0.37009121, 0.52580267, 0.37170041]])

In [34]:
np.random.rand(5,5)

array([[0.36614385, 0.99173753, 0.70080527, 0.26036039, 0.71680826],
       [0.60649287, 0.94674483, 0.98168743, 0.90732417, 0.51490987],
       [0.66031577, 0.77066203, 0.18881263, 0.36406361, 0.29042505],
       [0.76776889, 0.94765232, 0.16986565, 0.36290868, 0.41087191],
       [0.02616183, 0.39205171, 0.89908261, 0.12431762, 0.80988486]])

In [35]:
np.random.rand(5)

array([[[0.50464223, 0.79160084, 0.95520543, 0.30334742, 0.08030889],
        [0.20627074, 0.86530382, 0.26180361, 0.06813555, 0.74272266],
        [0.73166128, 0.5914512 , 0.90427659, 0.86824018, 0.42468237]],

       [[0.66742298, 0.4853008 , 0.07872836, 0.68667089, 0.11144378],
        [0.7596231 , 0.18424336, 0.91463392, 0.26464494, 0.48310885],
        [0.69421116, 0.88195955, 0.23750723, 0.53660149, 0.39368381]]])

In [38]:
np.random.randn(2,3,5)

array([[[-1.60530170e+00, -1.24819214e+00, -1.85363441e+00,
         -4.21031226e-01,  2.92109583e-03],
        [ 7.27439341e-01, -1.44022821e+00, -5.27471270e-01,
         -1.24116261e-01,  1.63258776e+00],
        [ 3.10452444e+00, -7.36554584e-01, -2.08766882e-01,
         -1.28227147e+00,  1.88812713e-01]],

       [[ 7.64657295e-01, -1.35986157e-01, -7.56802182e-01,
         -3.15041440e-02,  2.27279053e-01],
        [ 1.20622412e+00, -1.07481147e+00,  7.06767265e-01,
         -2.67787915e-01,  9.78608873e-01],
        [ 4.72434713e-01, -1.41189966e+00,  1.71722768e-01,
         -2.05924871e-01,  1.75227128e+00]]])

In [42]:
np.random.randint(15,555,10)

array([155,  84, 525, 545, 265,  59, 155, 277, 311,  59])

In [43]:
np.random.randint(1,100,20)

array([38, 67, 60, 45,  7, 53, 98, 35,  4, 19, 85, 52, 35, 71, 78, 58, 65,
       17,  1, 91])

In [61]:
m=np.arange(20)
m.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
m1=m.reshape(4,5)
print(m1[1,3])

8


In [64]:
m1[(1,3)]

8

In [65]:
m1[1:2,1:4]

array([[6, 7, 8]])

In [73]:
m1[2:4,0:2]

array([[10, 11],
       [15, 16]])

In [75]:
mat1.max()

19

In [76]:
mat1.min()

0

In [77]:
mat1.shape

(4, 5)

In [78]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [82]:
mat2=np.arange(5)
mat2[0:3]=100
print(mat2)

[100 100 100   3   4]


In [85]:
op1=np.array[1,2,3,4]
op2=op1+op1
op3=op1*op1
op1.sqrt()
op4=op1**2


TypeError: ignored

In [87]:
mat1=mat + mat
mat1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [88]:
mat1=mat * mat
mat1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [95]:
op1 = np.array([1,2,3,4])

In [97]:
op2 = op1+op1
print(op2)

[2 4 6 8]


In [98]:
op3 = op1*op1
print(op3)

[ 1  4  9 16]


In [105]:
np.sqrt(op1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [104]:
op4= op1 ** 2
print(op4)

[ 1  4  9 16]
